apiVersion: v1
kind: Service
metadata:
  labels:
    component: etcd
  name: etcd-svc-docker-desktop-xzm
  namespace: kube-system
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: https
      port: 2379
      nodePort: 32379
      protocol: TCP
      targetPort: 2379