apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2022-01-07T02:14:36Z","generation":2,"labels":{"app":"details","version":"v1"},"name":"details-v1","namespace":"default","resourceVersion":"5210796","uid":"6836624c-7e04-4fba-9079-7f03a657a5d8"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"details","version":"v1"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"details","version":"v1"}},"spec":{"containers":[{"image":"docker.io/istio/examples-bookinfo-details-v1:1.16.2","imagePullPolicy":"IfNotPresent","name":"details","ports":[{"containerPort":9080,"protocol":"TCP"}],"resources":{},"securityContext":{"runAsUser":1000},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"bookinfo-details","serviceAccountName":"bookinfo-details","terminationGracePeriodSeconds":30}}},"status":{"conditions":[{"lastTransitionTime":"2022-01-07T02:14:36Z","lastUpdateTime":"2022-01-07T02:14:36Z","message":"Deployment does not have minimum availability.","reason":"MinimumReplicasUnavailable","status":"False","type":"Available"},{"lastTransitionTime":"2022-01-07T02:24:37Z","lastUpdateTime":"2022-01-07T02:24:37Z","message":"ReplicaSet \"details-v1-79f774bdb9\" has timed out progressing.","reason":"ProgressDeadlineExceeded","status":"False","type":"Progressing"}],"observedGeneration":2,"replicas":1,"unavailableReplicas":1,"updatedReplicas":1}}
  creationTimestamp: "2022-01-07T02:44:35Z"
  generation: 1
  labels:
    app: details
    version: v1
  name: details-v1
  namespace: default
  resourceVersion: "5213980"
  uid: f2fff732-4427-4f54-b356-f76347cfccb8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: details
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: details
        version: v1
    spec:
      containers:
      - image: docker.io/istio/examples-bookinfo-details-v1:1.16.2
        imagePullPolicy: IfNotPresent
        name: details
        ports:
        - containerPort: 9080
          protocol: TCP
        resources: {}
        securityContext:
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: bookinfo-details
      serviceAccountName: bookinfo-details
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2022-01-07T02:44:35Z"
    lastUpdateTime: "2022-01-07T02:44:35Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2022-01-07T02:54:35Z"
    lastUpdateTime: "2022-01-07T02:54:35Z"
    message: ReplicaSet "details-v1-79f774bdb9" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
