apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/publicEndpoints: '[{"port":30379,"protocol":"TCP","serviceName":"default:redis","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"redis"},"name":"redis","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"redis"}},"template":{"metadata":{"labels":{"app":"redis"}},"spec":{"containers":[{"command":["sh","-c","redis-server /usr/local/redis/redis.conf"],"image":"redis:latest","livenessProbe":{"failureThreshold":3,"initialDelaySeconds":300,"periodSeconds":10,"successThreshold":1,"tcpSocket":{"port":6379},"timeoutSeconds":1},"name":"redis","ports":[{"containerPort":6379}],"readinessProbe":{"failureThreshold":3,"initialDelaySeconds":5,"periodSeconds":10,"successThreshold":1,"tcpSocket":{"port":6379},"timeoutSeconds":1},"resources":{"limits":{"cpu":"1000m","memory":"1024Mi"},"requests":{"cpu":"1000m","memory":"1024Mi"}},"volumeMounts":[{"mountPath":"/data","name":"data"},{"mountPath":"/usr/local/redis/redis.conf","name":"config","subPath":"redis.conf"}]}],"volumes":[{"name":"data","persistentVolumeClaim":{"claimName":"redis"}},{"configMap":{"name":"redis-config"},"name":"config"}]}}}}
  creationTimestamp: "2021-08-29T13:36:23Z"
  generation: 2
  labels:
    app: redis
  name: redis
  namespace: default
  resourceVersion: "5015770"
  uid: d722f54a-1050-4bb8-9942-b6061f7fbeb0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
    spec:
      containers:
      - command:
        - sh
        - -c
        - redis-server /usr/local/redis/redis.conf
        image: redis:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 300
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 6379
          timeoutSeconds: 1
        name: redis
        ports:
        - containerPort: 6379
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 6379
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "1"
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /usr/local/redis/redis.conf
          name: config
          subPath: redis.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: redis
      - configMap:
          defaultMode: 420
          name: redis-config
        name: config
status:
  conditions:
  - lastTransitionTime: "2021-08-29T13:36:23Z"
    lastUpdateTime: "2021-08-29T13:36:53Z"
    message: ReplicaSet "redis-f9f74787" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-01-05T03:03:37Z"
    lastUpdateTime: "2022-01-05T03:03:37Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 2
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
