apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"admissionregistration.k8s.io/v1","kind":"ValidatingWebhookConfiguration","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"webhook","app.kubernetes.io/name":"knative-serving","app.kubernetes.io/version":"1.1.0","serving.knative.dev/release":"v1.1.0"},"name":"validation.webhook.serving.knative.dev"},"webhooks":[{"admissionReviewVersions":["v1","v1beta1"],"clientConfig":{"service":{"name":"webhook","namespace":"knative-serving"}},"failurePolicy":"Fail","name":"validation.webhook.serving.knative.dev","rules":[{"apiGroups":["autoscaling.internal.knative.dev","networking.internal.knative.dev","serving.knative.dev"],"apiVersions":["*"],"operations":["CREATE","UPDATE","DELETE"],"resources":["metrics","podautoscalers","certificates","ingresses","serverlessservices","configurations","revisions","routes","services"],"scope":"*"}],"sideEffects":"None","timeoutSeconds":10}]}
  creationTimestamp: "2022-01-16T08:16:58Z"
  generation: 3
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: 1.1.0
    serving.knative.dev/release: v1.1.0
  name: validation.webhook.serving.knative.dev
  resourceVersion: "564552"
  uid: 37997cab-521e-447e-86a3-a655f5e53c7e
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNEekNDQWNHZ0F3SUJBZ0lSQVB6aXAxMjRkaHlsSFA5Wjg4OHZscGt3QlFZREsyVndNRHd4RkRBU0JnTlYKQkFvVEMydHVZWFJwZG1VdVpHVjJNU1F3SWdZRFZRUURFeHQzWldKb2IyOXJMbXR1WVhScGRtVXRjMlZ5ZG1sdQpaeTV6ZG1Nd0hoY05Nakl3TVRJeU1Ea3lOalE0V2hjTk1qSXdNVEk1TURreU5qUTRXakE4TVJRd0VnWURWUVFLCkV3dHJibUYwYVhabExtUmxkakVrTUNJR0ExVUVBeE1iZDJWaWFHOXZheTVyYm1GMGFYWmxMWE5sY25acGJtY3UKYzNaak1Db3dCUVlESzJWd0F5RUF4akNwc2FaWllKcXN6a01oSFcwZzIwYkUwL3I1dU4zS2o1RHJ5aE5FeElPagpnZGN3Z2RRd0RnWURWUjBQQVFIL0JBUURBZ0tFTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlRkOFYxTzdsZzdoa0ZzM0NDaHMrZTIKSEtyWVF6QnpCZ05WSFJFRWJEQnFnZ2QzWldKb2IyOXJnaGQzWldKb2IyOXJMbXR1WVhScGRtVXRjMlZ5ZG1sdQpaNEliZDJWaWFHOXZheTVyYm1GMGFYWmxMWE5sY25acGJtY3VjM1pqZ2lsM1pXSm9iMjlyTG10dVlYUnBkbVV0CmMyVnlkbWx1Wnk1emRtTXVZMngxYzNSbGNpNXNiMk5oYkRBRkJnTXJaWEFEUVFCcDVCRDZHeG9wUGorZzdBMFQKekRKTU5pSlNEVm9hMzdacDM1dGZQYllpNGV4TWZrTDFtVk8zR1RrNzFMLzRLVnU3cmtvZzVLUzAxby92V0JoUgpqbDhPCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: webhook
      namespace: knative-serving
      path: /resource-validation
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.webhook.serving.knative.dev
  namespaceSelector:
    matchExpressions:
    - key: webhooks.knative.dev/exclude
      operator: DoesNotExist
  objectSelector: {}
  rules:
  - apiGroups:
    - autoscaling.internal.knative.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - metrics
    - metrics/status
    scope: '*'
  - apiGroups:
    - autoscaling.internal.knative.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - podautoscalers
    - podautoscalers/status
    scope: '*'
  - apiGroups:
    - networking.internal.knative.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - certificates
    - certificates/status
    scope: '*'
  - apiGroups:
    - networking.internal.knative.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - ingresses
    - ingresses/status
    scope: '*'
  - apiGroups:
    - networking.internal.knative.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - serverlessservices
    - serverlessservices/status
    scope: '*'
  - apiGroups:
    - serving.knative.dev
    apiVersions:
    - v1
    - v1alpha1
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - configurations
    - configurations/status
    scope: '*'
  - apiGroups:
    - serving.knative.dev
    apiVersions:
    - v1
    - v1alpha1
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - revisions
    - revisions/status
    scope: '*'
  - apiGroups:
    - serving.knative.dev
    apiVersions:
    - v1
    - v1alpha1
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - routes
    - routes/status
    scope: '*'
  - apiGroups:
    - serving.knative.dev
    apiVersions:
    - v1
    - v1alpha1
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - services
    - services/status
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
