apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
  labels:
    eventing.knative.dev/release: "v1.1.0"
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/name: knative-eventing