apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-example-cfg-debug
  labels:
    app: admission-webhook-example-debug
webhooks:
  - name: mutating-example.qikqiak.com.debug
    clientConfig:
      service:
        name: admission-webhook-example-svc-debug
        namespace: default
        path: "/mutate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments"]
      # 主要在此处添加QoS的内容，创建，删除，更新的时候都要触发
      - operations: [ "CREATE","DETELE","UPDATE" ]
        apiGroups: ["stable.example.com", ""]
        apiVersions: ["v1"]
        resources: ["qoss"]
    namespaceSelector:
      matchLabels:
        admission-webhook-example: enabled