/*
/*
@Time : 2019/12/23 3:08 下午
@Author : tianpeng.du
@File : types
@Software: GoLand
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "ip/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Ips returns a IpInformer.
	Ips() IpInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Ips returns a IpInformer.
func (v *version) Ips() IpInformer {
	return &ipInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
