/*
/*
@Time : 2019/12/23 3:08 下午
@Author : tianpeng.du
@File : types
@Software: GoLand
*/

// Code generated by client-gen. DO NOT EDIT.

// Package fake has the automatically generated clients.
package fake
