/*
/*
@Time : 2019/12/23 3:08 下午
@Author : tianpeng.du
@File : types
@Software: GoLand
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "ip/pkg/client/clientset/versioned/typed/ip/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeRocduV1 struct {
	*testing.Fake
}

func (c *FakeRocduV1) Ips(namespace string) v1.IpInterface {
	return &FakeIps{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeRocduV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
