apiVersion: batch/v1
kind: Job
metadata:
  name: alpine-job
spec:
  template:
    metadata:
      name: alpine-job
    spec:
      restartPolicy: Never
      containers:
      - name: counter
        image: alpine:3.13
        command:
        - "bin/sh"
        - "-c"
        - "for i in 9 8 7 6 5 4 3 2 1; do echo $i; done"