---
apiVersion: v1
kind: Namespace
metadata:
  name: helloworld
  labels:
    serving.knative.dev/service: hello
    serving.knative.dev/visibility: cluster-local
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: helloworld
  labels:
    serving.knative.dev/service: hello
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      labels:
        app: hello
      annotations:
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
        - image: docker.io/xiazemin/helloworld-go
          env:
            - name: TARGET
              value: "World!"
