## PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis
  labels:
    type: local
spec:
  storageClassName: manual
  claimRef:
    name: redis
    namespace: default
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/xiazemin/source/k8s_learn/redis/test"