/*
/*
@Time : 2019/12/23 3:08 下午
@Author : tianpeng.du
@File : types
@Software: GoLand
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// IpListerExpansion allows custom methods to be added to
// IpLister.
type IpListerExpansion interface{}

// IpNamespaceListerExpansion allows custom methods to be added to
// IpNamespaceLister.
type IpNamespaceListerExpansion interface{}
