apiVersion: v1
kind: Pod
metadata:
 name: apple-configmap-volume
spec:
 containers:
 - name: apple-configmap-volume
   image: alpine:3.13
   imagePullPolicy: IfNotPresent
   args:
   - sleep
   - "86400"
   volumeMounts:
   - name: config-volume
     mountPath: "/projected-volume"
     readOnly: true
 volumes:
 - name: config-volume
   projected:
    sources:
    - configMap:
       name: dir-config