apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30000
      name: api
      protocol: TCP
    - port: 9001
      name: console
      targetPort: 9001
      nodePort: 30001
      protocol: TCP
  selector:
    app: minio