
name: Gitee repos mirror periodic job
on:
  workflow_dispatch:
  #schedule:
    # * is a special character in YAML so you have to quote this string
    # UTC 20:00 -> CST (China) 4:00, see https://datetime360.com/cn/utc-cst-china-time/
    #- cron: '43 * * * *'
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Mirror the Github organization repos to Gitee .
      uses: Yikun/hub-mirror-action@master
      with:
        go-version: 1.15
      
        # 必选，需要同步的Github用户（源）
        src: github/xiazemin
        # 必选，需要同步到的Gitee的用户（目的）
        dst: gitee/xzming
        # 必选，Gitee公钥对应的私钥，https://gitee.com/profile/sshkeys
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        # 必选，Gitee对应的用于创建仓库的token，https://gitee.com/profile/personal_access_tokens
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        # 如果是组织，指定组织即可，默认为用户user
        # account_type: org
        # 还有黑、白名单，静态名单机制，可以用于更新某些指定库
        # static_list: repo_name

    #- name: Build
     # run: go build -v ./...

    #- name: Test
     # run: go test -v ./...
  

        # black_list: 'repo_name,repo_name2'
        # white_list: 'repo_name,repo_name2'
