/*
/*
@Time : 2019/12/23 3:08 下午
@Author : tianpeng.du
@File : types
@Software: GoLand
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "ip/pkg/apis/ip/v1"
	"ip/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type RocduV1Interface interface {
	RESTClient() rest.Interface
	IpsGetter
}

// RocduV1Client is used to interact with features provided by the rocdu.top group.
type RocduV1Client struct {
	restClient rest.Interface
}

func (c *RocduV1Client) Ips(namespace string) IpInterface {
	return newIps(c, namespace)
}

// NewForConfig creates a new RocduV1Client for the given config.
func NewForConfig(c *rest.Config) (*RocduV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &RocduV1Client{client}, nil
}

// NewForConfigOrDie creates a new RocduV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *RocduV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new RocduV1Client for the given RESTClient.
func New(c rest.Interface) *RocduV1Client {
	return &RocduV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *RocduV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
